name: Contracts Deployment
on:
  push:
    branches: [ main ]
    paths: [ fc-community-contracts/src/** ]
jobs:
  deploy-contract:
    runs-on: ubuntu-latest
    env:
      CONTRACT_PATH: src/FactChainCommunity.sol:FactChainCommunity
      ETH_RPC_NAME: eth-sepolia
      CHAIN_ID: 11155111
      ETH_RPC_URL: ${{ secrets.RPC_ETH_SEPOLIA_HTTPS }}
      PRIVATE_KEY: ${{ secrets.DEPLOYER_PK }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_SEPOLIA_API_KEY }}
      OWNER_ADDRESS: ${{ vars.OWNER_ADDRESS }}
      ETHERSCAN_URL: https://sepolia.etherscan.io
    permissions: write-all
    defaults:
      run:
        working-directory: ./fc-community-contracts
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Deploy contract
        id: deploy
        run: |
          forge build
          createOutput=`forge create $CONTRACT_PATH --verify --json --rpc-url=$ETH_RPC_URL --private-key=$PRIVATE_KEY --constructor-args $OWNER_ADDRESS`
          echo "forge create output:\n\n$createOutput"
          deploymentOutput=`echo "${createOutput}" | head -1`
          echo "deploymentOutput=$deploymentOutput" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v3
        with:
          name: fc-community.abi.json
          path: ./fc-community-contracts/out/FactChainCommunity.sol/FactChainCommunity.json

      - name: Log detail of deployment
        run: |
          echo "# Contract deployed to $ETH_RPC_NAME :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "- Deployer: [${{ fromJson(steps.deploy.outputs.deploymentOutput).deployer }}](${ETHERSCAN_URL}/address/${{ fromJson(steps.deploy.outputs.deploymentOutput).deployer }})" >> $GITHUB_STEP_SUMMARY
          echo "- Deployed to: [${{ fromJson(steps.deploy.outputs.deploymentOutput).deployedTo }}](${ETHERSCAN_URL}/address/${{ fromJson(steps.deploy.outputs.deploymentOutput).deployedTo }})" >> $GITHUB_STEP_SUMMARY
          echo "- Transaction hash: [${{ fromJson(steps.deploy.outputs.deploymentOutput).transactionHash }}](${ETHERSCAN_URL}/tx/${{ fromJson(steps.deploy.outputs.deploymentOutput).transactionHash }})" >> $GITHUB_STEP_SUMMARY
