name: CI
on:
  push:
    branches: [ main ]
    paths: [ tm-community-contracts/** ]
jobs:
  deploy-contract:
    runs-on: ubuntu-latest
    permissions: write-all
    defaults:
      run:
        working-directory: ./tm-community-contracts
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Deploy to Sepolia
        id: deploy
        env:
          ETH_RPC_NAME: eth-sepolia
          ETH_RPC_URL: ${{ secrets.RPC_ETH_SEPOLIA_HTTPS }}
          PRIVATE_KEY: ${{ secrets.TM_SEPOLIA_DEPLOYER_PK }}
          OWNER: ${{ vars.TM_SEPOLIA_OWNER_ADDRESS }}
        run: |
          forge build
          createOutput=`forge create TrueMintCommunity --json --rpc-url=$ETH_RPC_URL --private-key=$PRIVATE_KEY --constructor-args $OWNER`
          echo "createOutput=$createOutput" >> $GITHUB_OUTPUT
      - name: Log detail of deployment
        run: |
          echo "# Contract deployed to Sepolia** :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "- Deployer: [${{ fromJson(steps.deploy.outputs.createOutput).deployer }}](https://sepolia.etherscan.io/address/${{ fromJson(steps.deploy.outputs.createOutput).deployer }})" >> $GITHUB_STEP_SUMMARY
          echo "- Deployed to: [${{ fromJson(steps.deploy.outputs.createOutput).deployedTo }}](https://sepolia.etherscan.io/address/${{ fromJson(steps.deploy.outputs.createOutput).deployedTo }})" >> $GITHUB_STEP_SUMMARY
          echo "- Transaction hash: [${{ fromJson(steps.deploy.outputs.createOutput).transactionHash }}](https://sepolia.etherscan.io/tx/${{ fromJson(steps.deploy.outputs.createOutput).transactionHash }})" >> $GITHUB_STEP_SUMMARY
