name: Contracts Code Checks
on:
  push:
    branches: [ main ]
    paths: [ fc-community-contracts/** ]
  pull_request:
    branches: [ main ]
    paths: [ fc-community-contracts/** ]
jobs:
  code-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fc-community-contracts
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Build contracts
        run: forge build

      - name: Run tests
        run: forge test -vvv
