name: Deploy main contract
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy-contract:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Deploy an implementation and its proxy
        uses: YBadiss/deploy-contract/proxy@main
        id: deploy
        with:
          implementation-contract-name: 'FactchainCommunity'
          proxy-contract-name: 'FactchainProxy'
          call-args: '"initialize(address)" "${{ vars.OWNER_ADDRESS }}"'
          parent-dir: 'fc-community-contracts'
          chain-id: '11155111'
          rpc-url: ${{ secrets.RPC_ETH_SEPOLIA_HTTPS }}
          deployer-pk: ${{ secrets.DEPLOYER_PK }}
          verify: true
          etherscan-url: 'https://sepolia.etherscan.io'
          etherscan-api-key: ${{ secrets.ETHERSCAN_SEPOLIA_API_KEY }}
