name: Deploy contracts
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      main-contract: ${{ steps.changes.outputs.main-contract }}
      nft-contract: ${{ steps.changes.outputs.nft-contract }}
      sft-contract: ${{ steps.changes.outputs.sft-contract }}
      x-contract: ${{ steps.changes.outputs.x-contract }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            main-contract:
              - 'fc-community-contracts/src/FactchainCommunity.sol'
            nft-contract:
              - 'fc-community-contracts/src/FactchainNFT.sol'
            sft-contract:
              - 'fc-community-contracts/src/FactchainSFT.sol'
            x-contract:
              - 'fc-community-contracts/src/XCommunityNotes.sol'
          token: ''
  deploy-main-contract:
    runs-on: ubuntu-latest
    needs:
      - changes
    if: needs.changes.outputs.main-contract == 'true'
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Deploy new implementation of main contract
        uses: YBadiss/deploy-contract/proxy@main
        id: deploy
        with:
          implementation-contract-name: 'FactchainCommunity'
          proxy-contract-address: ${{ vars.FACTCHAIN_COMMUNITY_PROXY_ADDRESS }}
          call-args: ''
          parent-dir: 'fc-community-contracts'
          chain-id: '11155111'
          rpc-url: ${{ secrets.RPC_ETH_SEPOLIA_HTTPS }}
          deployer-pk: ${{ secrets.DEPLOYER_PK }}
          verify: true
          etherscan-url: 'https://sepolia.etherscan.io'
          etherscan-api-key: ${{ secrets.ETHERSCAN_SEPOLIA_API_KEY }}
