name: Deploy NFT contract
on:
  push:
    branches: [ main ]
    paths:
      - fc-community-contracts/src/FactChainNFT.sol
      - fc-community-contracts/src/utils/Ownable.sol
  workflow_dispatch:
jobs:
  deploy-contract:
    runs-on: ubuntu-latest
    env:
      CONTRACT_NAME: FactChainNFT
      CHAIN_ID: 11155111
      ETH_RPC_URL: ${{ secrets.RPC_ETH_SEPOLIA_HTTPS }}
      PRIVATE_KEY: ${{ secrets.DEPLOYER_PK }}
      ETHERSCAN_URL: https://sepolia.etherscan.io
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_SEPOLIA_API_KEY }}
      OWNER_ADDRESS: ${{ vars.OWNER_ADDRESS }}
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: YBadiss/deploy-contract@v1
        with:
          contract-name: 'FactChainNFT'
          parent-dir: 'fc-community-contracts'
          chain-id: '11155111'
          rpc-url: ${{ secrets.RPC_ETH_SEPOLIA_HTTPS }}
          deployer-pk: ${{ secrets.DEPLOYER_PK }}
          constructor-args: '${{ vars.OWNER_ADDRESS }} https://gateway.pinata.cloud/ipfs/'
          verify: true
          etherscan-url: 'https://sepolia.etherscan.io'
          etherscan-api-key: ${{ secrets.ETHERSCAN_SEPOLIA_API_KEY }}
