name: Extension Code Checks
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths: [ fc-community-extension/** ]
jobs:
  code-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fc-community-extension
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Run checks
        run: yarn ci
