name: Extension Packaging
on:
  push:
    branches: [ main ]
    paths: [ fc-community-extension/** ]
  pull_request:
    branches: [ main ]
    paths: [ fc-community-extension/** ]
jobs:
  deploy-contract:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fc-community-extension
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Package extension
        run: |
          yarn install
          yarn run repack

      - uses: actions/upload-artifact@v3
        with:
          name: fc-community-extension.zip
          path: ./fc-community-extension/release/fc-community-extension-v*.zip
